### ISSUE TITLE
增加ERP后台，web形式展示，连锁经营方便统一管理

### ISSUE THREAD

**Issue by LoveesYe** [densen2014/docs#1]
![7HDAFFS65X{RCMI$U@885JN](https://user-images.githubusercontent.com/109154433/178995361-45decba3-cb26-4c77-a5ec-c94e8d8fd16d.png)

**Comment by LoveesYe** [comment]
1.所有连锁店的优惠卷可以共享,能在所有的连锁店内使用
2.意思是所有的VIP卡预付款，能在所有连锁店内使用
3.某些大型家电和家居有产品保修的，得有这个功能啊,方便有记录,可以查询发回厂家维修的，也要给客户提供单据吧
4.我没理解你说的第四点是什么,我的意思是ERP后台能集中统一管理每家连锁分店的意思

**Comment by densen2014** [comment]
产品保修做了后, 完全无下文, 关闭issue
