### ISSUE TITLE
便捷条码打印新版多了空行,没以前紧凑

### ISSUE THREAD

**Issue by jiebcn** [densen2014/docs#19]
小票打印机打印货架标签的字体调整失效

**Comment by densen2014** [comment]
![image](https://user-images.githubusercontent.com/8428709/223165110-7944acf4-6aa1-4fb9-8501-d8dfee726d68.png)

左边是今天的

右边是以前

![image](https://user-images.githubusercontent.com/8428709/223165212-a7dd86fc-51c8-41ee-ab29-cf39db71476a.png)
