### ISSUE TITLE
新版商品保质期提醒的页面，会卡住停顿

### ISSUE THREAD

**Issue by jiebcn** [densen2014/docs#20]
新版商品保质期提醒的页面，会卡住停顿

**Comment by jiebcn** [comment]
![TEST](https://user-images.githubusercontent.com/126505020/224307449-103d8c03-b5a0-4c05-ab2b-bbe57d0463ac.jpg)

**Comment by jiebcn** [comment]
@densen2014 @BOWANG599 @DENSEN-BIN

**Comment by densen2014** [comment]
发了就行, 不用圈人,都有邮件通知的

**Comment by densen2014** [comment]
修好了, 0310-beta.exe
