### ISSUE TITLE
触摸屏需求

### ISSUE THREAD

**Issue by HIMOZHU** [densen2014/docs#22]
客户反馈需要零售版触摸屏功能
1：登录界面需要
2：收银界面需要
类似如下
![4db861b7f01b27f025e77d0120c4422](https://github.com/densen2014/docs/assets/133499426/99bdac4c-a281-4ee6-8ebf-3a38f004aa95)
![e39702e9fb0c4fa23c6dd6fb29cac65](https://github.com/densen2014/docs/assets/133499426/8d872afe-d948-43ed-aaa0-0623c70ab512)
![WeChat截图_20230513124142](https://github.com/densen2014/docs/assets/133499426/5ab69fa7-1f3d-486f-b9ae-780655ff401b)

**Comment by HIMOZHU** [comment]
这样的话，主机入单，副机算账的可以全触摸屏操作了

**Comment by densen2014** [comment]
图片终于弄进来了,不简单啊小海

**Comment by HIMOZHU** [comment]
静静的等候佳音

**Comment by densen2014** [comment]
https://file2.app1.es/POS/230525-beta.exe

- 触摸屏, 销售界面和登录界面
