### ISSUE TITLE
客户附加税挂单以后，调单错误提示，以及客户税率需要重新选择的问题

### ISSUE THREAD

**Issue by jiebcn** [densen2014/docs#25]
新版本 BUG  
1 软件税率调整为不含税，默认客户也是不含税，在选择此客户，输入订单以后，挂单，再重新调入，默认发票勾选会丢失，
2  同样软件税率为不含税，选择的客户为需要增加附加税时 ，操作挂单，再调单是，出现税率和默认税率不符提示，选择客户税率，会出错。然后单据被锁定，选择默认税率，则所选税率被去除，变为订单
3  客户税率每月报表，不完善，
月报表，客户IVA 详单，没有统计银行转账记录，且 票脚无总结  
报表中心新功能，税务详单，统计出口税，计算总数，出现数据重复计数   
请尽快解决，谢谢

**Comment by densen2014** [comment]
每一条都单独分开写issue, 单一职责处理. 最好附上截图画线说明, 复现步骤

**Comment by densen2014** [comment]
1. 这个发票勾不能保存的, 一直不能保存,将来也是.
2. 挂单调单不能保存你说的这些设置,一直都是
3. 第三点请单独开issue详细说明.带截图

**Comment by densen2014** [comment]
0714
7.8.1
报表中心的发票税务详单和发票税务详单带前缀 出口税的不含税会双倍 #973

**Comment by densen2014** [comment]
7天内不提供新的回复issue将会被关闭
