### ISSUE TITLE
副机反应很慢

### ISSUE THREAD

**Issue by aaronameixa** [densen2014/docs#27]
你好，
我这里有 一台主机跟二台副机。我这两台副机反应特别慢。 
1.主机跟副机链接通过LAN本地连接，而数据库（我有二个数据库，一个在磁盘而另外一个在USB）,不管是在磁盘还是在USB 副机反应还是很卡。
2.之前我的原本是主机（非常的流畅）转成了副机就变得非常的卡顿。不是电脑本身卡顿
能帮我看看是什么问题

**Comment by aaronameixa** [comment]
1.usb数据库是必要的
3. 主机算账不卡

**Comment by densen2014** [comment]
按流程测试，报告结果。

**Comment by densen2014** [comment]
> 仅仅局域网的话，千万别设置dns和网关

仅仅局域网的话，千万别设置dns和网关

**Comment by densen2014** [comment]
7天内不提供新的回复issue将会被关闭
