### ISSUE TITLE
FreeRes餐馆触屏 20221022

### ISSUE THREAD

**Issue by yqfcpy** [densen2014/docs#5]
客户需求和bug
1、历史报表有具体时间 如下图
![mmexport1666476167086](https://user-images.githubusercontent.com/51460766/197363973-1a529642-3dfc-41fd-94fd-60573e8cceec.png)
2、bug
小票中如果有2个以上的菜 小票中总计不对 如图
![IMG_20221022_192418](https://user-images.githubusercontent.com/51460766/197364056-fa274954-b1de-4b86-8726-f73277f2bb5a.jpg)
3、客人是美甲店 所有税率是21%
月结小票文字还是写的10%  就把显示10% 给他改成21%  只是显示显示显示 不是傻逼客人那个多税率问题 如图
![IMG_20221022_184031_edit_40192742280135.jpg](https://user-images.githubusercontent.com/51460766/197364661-95d1323c-820b-4891-bfa1-9b540dee7fd8.jpg)

**Comment by densen2014** [comment]
都已经修复和更新
